package io.github.mgerhardy.trivy

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import org.gradle.process.ExecOperations
import org.gradle.work.DisableCachingByDefault
import java.io.File
import javax.inject.Inject

/**
 * Generates a Software Bill of Materials (SBOM) in CycloneDX or SPDX format
 * using Trivy's filesystem scanner. Reuses the same lock files generated by
 * [LockGradleTask] and [LockNpmTask] to ensure dependency resolution is consistent
 * with the vulnerability scan.
 */
@DisableCachingByDefault(because = "SBOM content depends on resolved dependencies at scan time")
abstract class TrivySbomTask @Inject constructor(
    private val execOps: ExecOperations
) : DefaultTask() {

    @get:InputFile
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val trivyBinary: RegularFileProperty

    @get:Internal
    abstract val scanTarget: DirectoryProperty

    @get:Internal
    abstract val lockFilesDir: DirectoryProperty

    /**
     * SBOM output format. Supported values: "cyclonedx", "spdx-json".
     * Default: "cyclonedx"
     */
    @get:Input
    abstract val sbomFormat: Property<String>

    /**
     * Output file for the generated SBOM.
     */
    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @get:Optional @get:Input
    abstract val cacheDir: Property<String>

    @get:Input
    abstract val skipDbUpdate: Property<Boolean>

    @get:Optional @get:Input
    abstract val dbRepository: Property<String>

    @get:Input
    abstract val excludeDirs: ListProperty<String>

    @get:Input
    abstract val skipFiles: ListProperty<String>

    @get:Optional @get:Input
    abstract val ignoreFile: Property<String>

    @get:Input
    abstract val additionalArgs: ListProperty<String>

    @TaskAction
    fun generate() {
        val binary = trivyBinary.get().asFile.absolutePath
        val target = scanTarget.get().asFile

        val copiedFiles = mutableListOf<File>()
        try {
            if (lockFilesDir.isPresent) {
                val lockDir = lockFilesDir.get().asFile
                if (lockDir.exists()) {
                    lockDir.walk()
                        .filter { it.isFile && (it.name == "gradle.lockfile" || it.name == "package-lock.json") }
                        .forEach { lock ->
                            val rel = lock.relativeTo(lockDir)
                            val dest = File(target, rel.path)
                            if (!dest.exists()) {
                                dest.parentFile.mkdirs()
                                lock.copyTo(dest)
                                copiedFiles.add(dest)
                            }
                        }
                }
            }

            val format = sbomFormat.get()
            val args = mutableListOf(binary, "fs")
            args.addAll(listOf("--format", format))
            args.addAll(listOf("--output", outputFile.get().asFile.absolutePath))

            if (cacheDir.isPresent) args.addAll(listOf("--cache-dir", cacheDir.get()))
            if (skipDbUpdate.get()) args.add("--skip-db-update")
            if (dbRepository.isPresent) args.addAll(listOf("--db-repository", dbRepository.get()))
            if (ignoreFile.isPresent) args.addAll(listOf("--ignorefile", ignoreFile.get()))

            excludeDirs.get().forEach { args.addAll(listOf("--skip-dirs", it)) }
            skipFiles.get().forEach { args.addAll(listOf("--skip-files", it)) }

            // SBOM generation should not fail the build — it's informational
            args.addAll(listOf("--scanners", "license"))
            args.addAll(additionalArgs.get())
            args.add(target.absolutePath)

            logger.lifecycle("Generating SBOM ($format) for ${target.absolutePath}")
            outputFile.get().asFile.parentFile.mkdirs()
            val result = execOps.exec { spec ->
                spec.commandLine(args)
                spec.isIgnoreExitValue = true
            }
            if (result.exitValue != 0) {
                throw GradleException("Trivy SBOM generation failed with exit code ${result.exitValue}")
            }
            logger.lifecycle("SBOM written to ${outputFile.get().asFile.absolutePath}")
        } finally {
            copiedFiles.forEach { it.delete() }
        }
    }
}
