package io.github.mgerhardy.trivy

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import org.gradle.process.ExecOperations
import org.gradle.work.DisableCachingByDefault
import java.io.File
import javax.inject.Inject

/**
 * Scans project dependencies for license compliance using Trivy's license scanner.
 * Reuses the same lock files generated by [LockGradleTask] and [LockNpmTask].
 *
 * Can be configured to fail the build when forbidden licenses (e.g., GPL, AGPL)
 * are detected in dependencies, supporting CRA and ISO 27001 A.5.19 compliance.
 */
@DisableCachingByDefault(because = "License results depend on resolved dependencies at scan time")
abstract class TrivyLicenseCheckTask @Inject constructor(
    private val execOps: ExecOperations
) : DefaultTask() {

    @get:InputFile
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val trivyBinary: RegularFileProperty

    @get:InputDirectory
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val scanTarget: DirectoryProperty

    @get:Internal
    abstract val lockFilesDir: DirectoryProperty

    /**
     * Output format for the license report. Default: "json".
     * Supported: "table", "json", "sarif".
     */
    @get:Input
    abstract val outputFormat: Property<String>

    /**
     * Output file for the license report.
     */
    @get:Optional @get:OutputFile
    abstract val outputFile: RegularFileProperty

    /**
     * Fail the build when forbidden licenses are found. Default: true.
     */
    @get:Input
    abstract val failOnForbidden: Property<Boolean>

    /**
     * License categories to treat as forbidden. Default: ["restricted", "forbidden"].
     * Trivy classifies licenses into: forbidden, restricted, reciprocal, notice, permissive, unencumbered, unknown.
     * See: https://github.com/aquasecurity/trivy/blob/main/pkg/licensing/category.go
     */
    @get:Input
    abstract val forbiddenCategories: ListProperty<String>

    /**
     * Specific SPDX license IDs to forbid regardless of category.
     * Example: ["GPL-3.0", "AGPL-3.0-only"]
     */
    @get:Input
    abstract val forbiddenLicenses: ListProperty<String>

    /**
     * Specific SPDX license IDs to allow regardless of category (overrides forbidden).
     * Example: ["LGPL-2.1"] — useful for libraries where dynamic linking is acceptable.
     */
    @get:Input
    abstract val allowedLicenses: ListProperty<String>

    @get:Optional @get:Input
    abstract val cacheDir: Property<String>

    @get:Input
    abstract val skipDbUpdate: Property<Boolean>

    @get:Optional @get:Input
    abstract val dbRepository: Property<String>

    @get:Input
    abstract val excludeDirs: ListProperty<String>

    @get:Input
    abstract val skipFiles: ListProperty<String>

    @get:Input
    abstract val additionalArgs: ListProperty<String>

    @TaskAction
    fun check() {
        val binary = trivyBinary.get().asFile.absolutePath
        val target = scanTarget.get().asFile

        val copiedFiles = mutableListOf<File>()
        try {
            if (lockFilesDir.isPresent) {
                val lockDir = lockFilesDir.get().asFile
                if (lockDir.exists()) {
                    lockDir.walk()
                        .filter { it.isFile && (it.name == "gradle.lockfile" || it.name == "package-lock.json") }
                        .forEach { lock ->
                            val rel = lock.relativeTo(lockDir)
                            val dest = File(target, rel.path)
                            if (!dest.exists()) {
                                dest.parentFile.mkdirs()
                                lock.copyTo(dest)
                                copiedFiles.add(dest)
                            }
                        }
                }
            }

            val args = mutableListOf(binary, "fs")
            args.addAll(listOf("--scanners", "license"))
            args.add("--license-full")
            args.addAll(listOf("--format", outputFormat.get()))

            if (outputFile.isPresent) args.addAll(listOf("--output", outputFile.get().asFile.absolutePath))
            if (cacheDir.isPresent) args.addAll(listOf("--cache-dir", cacheDir.get()))
            if (skipDbUpdate.get()) args.add("--skip-db-update")
            if (dbRepository.isPresent) args.addAll(listOf("--db-repository", dbRepository.get()))

            excludeDirs.get().forEach { args.addAll(listOf("--skip-dirs", it)) }
            skipFiles.get().forEach { args.addAll(listOf("--skip-files", it)) }

            // Build severity from forbidden categories
            val categories = forbiddenCategories.get()
            if (categories.isNotEmpty() && failOnForbidden.get()) {
                args.addAll(listOf("--severity", categories.joinToString(",")))
                args.addAll(listOf("--exit-code", "1"))
            }

            // Specific forbidden/allowed license overrides via --license-forbidden / --license-allowed (Trivy 0.57+)
            val forbidden = forbiddenLicenses.get()
            if (forbidden.isNotEmpty()) {
                forbidden.forEach { args.addAll(listOf("--license-forbidden", it)) }
            }
            val allowed = allowedLicenses.get()
            if (allowed.isNotEmpty()) {
                allowed.forEach { args.addAll(listOf("--license-allowed", it)) }
            }

            args.addAll(additionalArgs.get())
            args.add(target.absolutePath)

            logger.lifecycle("Running license compliance check on ${target.absolutePath}")
            val result = execOps.exec { spec ->
                spec.commandLine(args)
                spec.isIgnoreExitValue = true
            }

            when {
                failOnForbidden.get() && result.exitValue == 1 ->
                    throw GradleException("Trivy found dependencies with forbidden licenses (categories: ${categories.joinToString(", ")})")
                result.exitValue != 0 && result.exitValue != 1 ->
                    throw GradleException("Trivy license check failed with exit code ${result.exitValue}")
            }

            if (result.exitValue == 0) {
                logger.lifecycle("License check passed — no forbidden licenses detected")
            }
        } finally {
            copiedFiles.forEach { it.delete() }
        }
    }
}
